src/main/java/br/com/fanaticosporviagens/model/entity/PlanoViagem.java
package br.com.fanaticosporviagens.model.entity;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.Valid;

import org.hibernate.annotations.IndexColumn;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;
import org.joda.time.Interval;
import org.joda.time.LocalDate;
import org.joda.time.Period;
import org.springframework.util.AutoPopulatingList;

import br.com.fanaticosporviagens.acaousuario.AlvoAcao;
import br.com.fanaticosporviagens.infra.model.entity.EnumI18nUtil;
import br.com.fanaticosporviagens.infra.model.entity.EnumTypeInteger;
import br.com.fanaticosporviagens.infra.model.entity.GenericEnumUserType;

/**
 *
 * @author Pedro Sebba
 * @author Carlos Nascimento
 *
 */
@Entity
@Table(name = "drop_viagem")
@SequenceGenerator(name = "sequenceGenerator", sequenceName = "seq_viagem", allocationSize = 1)
@TypeDefs(value = {
        @TypeDef(name = "SituacaoViagem", typeClass = GenericEnumUserType.class, parameters = { @Parameter(name = "enumClass", value = "br.com.fanaticosporviagens.model.entity.PlanoViagem$SituacaoViagem") }),
        @TypeDef(name = "TipoPeriodoViagem", typeClass = GenericEnumUserType.class, parameters = { @Parameter(name = "enumClass", value = "br.com.fanaticosporviagens.model.entity.PlanoViagem$TipoPeriodoViagem") }),
        @TypeDef(name = "Visibilidade", typeClass = GenericEnumUserType.class, parameters = { @Parameter(name = "enumClass", value = "br.com.fanaticosporviagens.model.entity.TipoVisibilidade") }) })
@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false, unique = true)) })
public class PlanoViagem extends EntidadeGeradoraAcao<Long> implements Comentavel {

    /**
     * Classe que encapsula o numero dos dias e seus respectivos dias do mes
     *
     * @author carlosn
     *
     */
    public static class DiaViagem {

        public static List<DiaViagem> criarDiasViagem(final PlanoViagem planoViagem) {
            final List<DiaViagem> lista = new ArrayList<DiaViagem>();

            if (planoViagem.isPeriodoNaoDefinido()) {
                lista.add(new DiaViagem(1, null, planoViagem.getAtividades()));
            } else {

                LocalDate data = planoViagem.getDataInicio();
                if (planoViagem.getQuantidadeDias() != null) {
                    for (int i = 1; i <= planoViagem.getQuantidadeDias(); i++) {
                        lista.add(new DiaViagem(i, data, planoViagem.getAtividadesDoDia(i)));
                        if (data != null) {
                            data = data.plusDays(1);
                        }
                    }
                }
            }
            return lista;
        }

        public static DiaViagem criarDiaViagem(final PlanoViagem planoViagem, final Integer numeroDia) {
            LocalDate data = planoViagem.getDataInicio();
            if (data != null) {
                data = data.plusDays(numeroDia - 1);
            }
            return new DiaViagem(numeroDia, data, planoViagem.getAtividadesDoDia(numeroDia));
        }

        private final List<AtividadePlano> atividadePlanos;

        private LocalDate data;

        private Integer numeroDia;

        private DiaViagem(final Integer numeroDia, final LocalDate data, final List<AtividadePlano> atividadePlanos) {
            this.numeroDia = numeroDia;
            this.data = data;
            this.atividadePlanos = atividadePlanos;
        }

        public List<AtividadePlano> getAtividades() {
            return this.atividadePlanos;
        }

        public LocalDate getData() {
            return this.data;
        }

        public String getDiaMes() {
            if (this.data != null) {
                return this.data.toString("dd");
            }
            return null;
        }

        public String getDiaMesComMesCurto() {
            if (this.data != null) {
                return this.data.toString("dd 'de' MMM");
            }
            return null;
        }

        public String getDiaMesComMesLongo() {
            if (this.data != null) {
                return this.data.toString("dd 'de' MMMM");
            }
            return null;
        }

        public String getDiaSemanaCurto() {
            if (this.data != null) {
                return this.data.toString("EEE");
            }
            return null;
        }

        public String getDiaSemanaCurtoDiaMesComMesCurto() {
            if (this.data != null) {
                return this.data.toString("EEE, dd 'de' MMM");
            }
            return null;
        }

        public String getDiaSemanaCurtoDiaMesComMesLongo() {
            if (this.data != null) {
                return this.data.toString("EEE, dd 'de' MMMM");
            }
            return null;
        }

        public String getDiaSemanaLongo() {
            if (this.data != null) {
                return this.data.toString("EEEE");
            }
            return null;
        }

        public String getDiaSemanaLongoDiaMesComMesLongo() {
            if (this.data != null) {
                return this.data.toString("EEEE, dd 'de' MMMM");
            }
            return null;
        }

        public String getMes() {
            if (this.data != null) {
                return this.data.toString("MM");
            }
            return null;
        }

        public String getMesCurto() {
            if (this.data != null) {
                return this.data.toString("MMM");
            }
            return null;
        }

        public String getMesLongo() {
            if (this.data != null) {
                return this.data.toString("MMMM");
            }
            return null;
        }

        public Integer getNumero() {
            return this.numeroDia;
        }

        public Integer getNumeroDiaMes() {
            if (this.data != null) {
                return this.data.getDayOfMonth();
            }
            return null;
        }

        public Integer getNumeroMes() {
            if (this.data != null) {
                return this.data.getMonthOfYear();
            }
            return null;
        }

        public boolean getPossuiAtividadesAExibir() {
            if (this.atividadePlanos == null || this.atividadePlanos.isEmpty()) {
                return false;
            } else {
                for (final AtividadePlano atividadePlano : this.atividadePlanos) {
                    if (atividadePlano.isVisivel()) {
                        return true;
                    }
                }
                return false;
            }
        }

        public Integer getQuantidadeAtividades() {
            return this.atividadePlanos != null ? this.atividadePlanos.size() : null;
        }

        public void setData(final LocalDate data) {
            this.data = data;
        }

        public void setNumeroDia(final Integer numeroDia) {
            this.numeroDia = numeroDia;
        }
    }

    public enum SituacaoViagem implements EnumTypeInteger {
        EXECUTADA(1, "Executada"),
        PLANEJADA(2, "Planejada");

        private final EnumI18nUtil util;

        SituacaoViagem(final int codigo, final String... descricoes) {
            this.util = new EnumI18nUtil(codigo, new String[] { "pt_BR" }, descricoes);
        }

        @Override
        public Integer getCodigo() {
            return this.util.getCodigo();
        }

        @Override
        public String getDescricao() {
            return this.util.getDescricao();
        }
    }

    public enum TipoPeriodoViagem implements EnumTypeInteger {

        NAO_DEFINIDO(3, "Não definido"),
        POR_DATAS(1, "Informar datas"),
        POR_QUANTIDADE_DIAS(2, "Quantidade de dias");

        private final EnumI18nUtil util;

        TipoPeriodoViagem(final int codigo, final String... descricoes) {
            this.util = new EnumI18nUtil(codigo, new String[] { "pt_BR" }, descricoes);
        }

        @Override
        public Integer getCodigo() {
            return this.util.getCodigo();
        }

        @Override
        public String getDescricao() {
            return this.util.getDescricao();
        }
    }

    private static final long serialVersionUID = -2499849897982827294L;

    @OneToMany(mappedBy = "planoViagem", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("ordem")
    @IndexColumn(base = 1, name = "ORDEM")
    private List<AtividadePlano> atividadePlanos = new ArrayList<AtividadePlano>();

    @Column(name = "compartilhada_facebook", nullable = true)
    private Boolean compartilhadaFacebook = false;

    @Column(name = "compartilhada_twitter", nullable = true)
    private Boolean compartilhadaTwitter = false;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "criador", nullable = false)
    private Usuario criador;

    @Column(name = "criador_viaja", nullable = true)
    private Boolean criadorViaja = true;

    @Column(name = "data_fim")
    @Type(type = "org.jadira.usertype.dateandtime.joda.PersistentLocalDate")

src/main/webapp/WEB-INF/views/planoViagem/diario/carrosselFotos.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib tagdir="/WEB-INF/tags" prefix="fan" %>

<style>

.box-foto-div {
    position: relative;
}

.box-foto-item div.opcoes {
    display: none;
    position: absolute;
    left: 10px;
    top: 10px;
    overflow: hidden;
}

.box-foto-item div.opcoes:hover {
    display: block;
}

.box-foto-item:hover div.opcoes {
    display: block;
}
</style>

<c:if test="${param.exibirOpcoes}">
  <%@include file="../../fotos/acoesSobreFoto.jsp" %>
</c:if>

<c:set var="width" value="${width != null ? width : 770}"/>
<c:set var="slideAmount" value="${slideAmount != null ? slideAmount : 4}"/>

<div>
    <c:if test="${atividade.possuiFotos}">
      <div class="borda-arredondada" style="padding: 15px; display: ''; margin-left: 0px; position: relative; width: ${width}px; height: 175px;">
        <div id="fotos-atividade-${atividade.id}" class="theme1">
                        
            <ul style="list-style: none;">
                <c:forEach items="${atividade.fotos}" var="foto" varStatus="status">
                    <li id="form-edit-foto-${foto.id}" class="box-foto-item">
                        <a id="box-foto-link-${foto.id}" href="<c:url value="/fotos/exibir/${foto.id}?i=${status.index}&u=${status.last}"/>" 
                           class="fancybox box-foto" title="" data-id-foto="${foto.id}" data-index-foto="${status.index}" 
                           data-prev-index="${status.index - 1}" data-next-index="${status.index + 1}">
                            
                            <i class="carrossel-thumb borda-arredondada" data-foto-id="${foto.id}" 
                               style="background-image: url('<c:url value="${foto.urlAlbum}"/>'); height: 130px; width: 170px;"></i>
                               
                            <p style="min-height: 50px;">
                                <br/>
                                <small>
                                    ${foto.descricao}
                                </small>
                            </p>
                        </a>
                        <c:if test="${param.exibirOpcoes}">
                          <div class="btn-group opcoes" style="position: absolute; left: 5px; top: 5px;">
                            <a href="#" class="btn btn-remover-foto" data-atividade-id="${atividade.id}" data-foto-id="${foto.id}" title="Remover esta foto">
                                <i class="icon-trash"></i>
                            </a>
                          </div>
                        </c:if>                    
                    </li>
                </c:forEach>
            </ul>
            <div class="toolbar">
                <div class="left"></div><div class="right"></div>
            </div>
        </div>
      </div>
      
      <div id="modal-foto" class="modal hide fade" role="dialog" >
        <div class="modal-header" style="border-bottom: 0px;">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body" style="overflow: hidden; max-height: 800px; min-width: 960px;">
            <div id="modal-foto-body"></div>
        </div>
      </div>
      
    </c:if>
</div>

<script>
	$(document).ready(function () {
        jQuery('#fotos-atividade-${atividade.id}').services({
            width: ${width - 30},
            height: 130,
            slideAmount: ${slideAmount},
            slideSpacing: 10,
            touchenabled: 'on',
            mouseWheel: 'off',
            //transition: 4,
            carousel: 'off',
            hoverAlpha: 'on',
            //slideshow: 5000
        });
        
        $('a.fancybox').click(function(e) {
            e.preventDefault();
            var idFoto = $(this).data('id-foto');
            // pegar a url da foto
            var url = $('#box-foto-link-' + idFoto).attr('href');
            $('#modal-foto-body').load(url, function() {
                $('#modal-foto').modal().css({
                    /*'width': function () { 
                         return ($(document).width() * .9) + 'px';  
                    },
                    'margin-left': function () { 
                        return -($(this).width() / 2); 
                    }*/
                    width: 'auto',
                    'margin-left': function () {
                        return -($(this).width() / 2);
                    }
                });                 
                $('#modal-foto').modal('show');
                
            });
        });        
	});
</script>

src/main/webapp/WEB-INF/views/planoViagem/diario/exibirAtividadesDia.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib prefix="joda" uri="http://www.joda.org/joda/time/tags" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="fan" %>

<%--             <div class="tab-pane active" id="tab-capa">
        
                <div>
                
                    <h3 class="green">Início</h3>
                
                    <span class="texto-blog">
                        ${diario.textoIntroducao}
                    </span>
                
                </div>
                
                <div class="horizontalBar"></div>
                
            </div> --%>
            

<div class="row" style="margin-left: 0px;">

  <fieldset style="background-color: #F8F8F8;">

    <legend>
      <h3>${diaViagem.diaSemanaLongoDiaMesComMesLongo}</h3>
    </legend>                

    <div class="span3" style="margin-left: 0px;">
  
      <div style="max-height: 1px;">
      &nbsp;
      </div>
  
      <div class="bs-docs-sidebar">
        <ul class="nav nav-list bs-docs-sidenav span3" style="margin-left: 0px; z-index: 99;">
          <c:if test="${diario.viagem.quantidadeDias > 1}">
            <li class="borda-arredondada-cima" style="background-color: #6FC46F; min-height: 22px; text-align: center; padding-top: 4px;">
                <c:if test="${diaViagem.numero > 1}">
                    <i class="icon-arrow-left icon-white left mudar-dia" style="margin-left: 5px; cursor: pointer;" title="Dia anterior" data-proximo-dia="${diaViagem.numero - 1}"></i>
                </c:if>
                <strong class="white">${diaViagem.numero}º dia</strong>
                <c:if test="${diaViagem.numero < diario.viagem.quantidadeDias}">
                    <i class="icon-arrow-right icon-white right mudar-dia" style="margin-right: 5px; cursor: pointer;" title="Próximo dia" data-proximo-dia="${diaViagem.numero + 1}"></i>
                </c:if>
            </li>
          </c:if>
          
          <c:if test="${diaViagem.possuiAtividadesAExibir}">
            <c:forEach items="${diaViagem.atividades}" var="atividade" varStatus="status">
              <c:if test="${not atividade.oculta}">
                <li class="${status.index == 0 ? 'active' : ''}">
                  <a href="#atividade-${atividade.id}">
                    <c:if test="${atividade.possuiTitulo}">
                        ${atividade.titulo} - 
                    </c:if> 
                    <i class="icon-chevron-right"></i> ${atividade.local.nome}
                  </a>
                </li>
              </c:if>
            </c:forEach>
          </c:if>
          <c:if test="${not diaViagem.possuiAtividadesAExibir}">
            <li style="min-height: 25px; text-align: center; margin-top: 5px;">
                Nenhuma atividade neste dia
            </li>
          </c:if>
        </ul>
      </div>
    </div>        

    <div id="tab-content" class="span12">
      <div id="tab-dia-${diaViagem.numero}">
      
        <c:if test="${not diaViagem.possuiAtividadesAExibir}">
            <fieldset style="background-color: #FFF;">
                <div class="blank-state">
                    <div class="row" style="text-align: center;">
                        <div>
                            <img src="<c:url value="/resources/images/icons/mini/128/Time-3.png" />" width="90" height="90" />
                            <h3>Nenhuma atividade neste dia</h3>
                            <p>
                                <c:choose>
                                  <c:when test="${usuario.id == diario.viagem.criador.id}">
                                      Você
                                  </c:when>
                                  <c:otherwise>
                                      Este usuário
                                  </c:otherwise>
                                </c:choose>
                                não registrou nenhuma atividade neste dia.
                            </p>
                        </div>
                    </div>
                </div>            
            </fieldset>
        </c:if>
        
        <c:if test="${diaViagem.possuiAtividadesAExibir}">
      
          <c:forEach items="${diaViagem.atividades}" var="atividade" varStatus="status">
        
            <c:if test="${not atividade.oculta}">
        
              <section id="atividade-${atividade.id}">
              
                <fieldset style="background-color: #FFF;">
                
                    <legend>
                      <h3 class="green">
                        <c:choose>
                          <c:when test="${not empty atividade.titulo}">
                            ${atividade.titulo}
                          </c:when>
                          <c:otherwise>
                            <c:choose>
                              <c:when test="${atividade.hospedagem}">Hospedagem em</c:when>
                              <c:otherwise>Visita a(o)</c:otherwise>
                            </c:choose>
                            <a href="#" target="_blank">${atividade.local.nome}</a>
                          </c:otherwise>
                        </c:choose>
                      </h3>
                    </legend>           
                
                    <h3 style="text-shadow: none;">
                        <p>
                            <c:if test="${atividade.dataInicio != null}">
                              <small>
                                ${diaViagem.diaSemanaLongoDiaMesComMesLongo}
                                -
                              </small>
                            </c:if>
                            <small class="blue">${atividade.local.nome}</small>
                            <%-- <small>${atividade.local.nomeCidadeComSiglaEstado}</small> --%>
                        </p>
                    </h3>
                    
                    <c:if test="${not atividade.preencheuDadosDiario}">
                        <div class="blank-state">
                            <div class="row" style="text-align: center;">
                                <div>
                                    <%-- <img src="<c:url value="/resources/images/icons/mini/128/Time-3.png" />" width="90" height="90" /> --%>
                                    <h3>Sem informações para exibir</h3>
                                    <p>
                                        <c:choose>
                                          <c:when test="${usuario.id == diario.viagem.criador.id}">
                                              Você
                                          </c:when>
                                          <c:otherwise>
                                              Este usuário
                                          </c:otherwise>
                                        </c:choose>
                                        ainda não adicionou informações para esta atividade.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </c:if>
                    
                    <c:if test="${atividade.possuiRelato}">
                      <fieldset>
                        <span class="texto-blog">
                            ${atividade.relato.texto}
                        </span>
                      </fieldset>
                    </c:if>
                    
                    <c:if test="${atividade.possuiFotos}">
                    
                        <fieldset style="background-color: #F8F8F8;">
                        
                            <legend>
                                <h4 class="green">Fotos</h4>
                            </legend>
                            
                            <div id="painel-fotos">
                                <c:set var="width" value="630"></c:set>
                                <c:set var="slideAmount" value="3"></c:set>
                                <%@include file="carrosselFotos.jsp" %>
                            </div>
                            
                        </fieldset>
                    
                    </c:if>
            
                    <c:if test="${atividade.possuiAvaliacao}">
                        <fieldset id="fieldset-avaliacao" style="background-color: #F8F8F8;">
                        
                            <legend>
                                
                                <div class="btn-group" data-toggle="buttons-checkbox" style="margin-bottom: 5px">
                                  <button id="btn-ver-avaliacao" type="button" class="btn btn-mini btn-success btn-exibir-painel" data-painel-id="painel-avaliacao-${atividade.id}">
                                    <i class="icon-eye-open icon-white"></i>
                                    Ver avaliação sobre este local
                                  </button>
                                </div>
                                
                            </legend>
                            
                            <div id="painel-avaliacao-${atividade.id}" style="display: none;">
                                <fan:avaliacao avaliacao="${atividade.avaliacao}"></fan:avaliacao>
                            </div>
                        
                        </fieldset>
                    </c:if>
                        
                    <c:if test="${atividade.possuiDicas}">
                        <fieldset id="fieldset-dicas" style="background-color: #F8F8F8;">
                            <legend>
                                <h4 class="green"></h4>
                                
                                <div class="btn-group" data-toggle="buttons-checkbox" style="margin-bottom: 5px">
                                  <button id="btn-ver-dicas" type="button" class="btn btn-mini btn-success btn-exibir-painel" data-painel-id="painel-dicas-${atividade.id}">
                                    <i class="icon-eye-open icon-white"></i>
                                    Ver dicas sobre este local
                                  </button>
                                </div>
                                
                            </legend>
                            
                            <div id="painel-dicas-${atividade.id}" style="display: none;">
                                <c:forEach items="${atividade.dicas}" var="dica">
                                    <fan:dica dica="${dica}"></fan:dica>
                                </c:forEach>
                            </div>
                        </fieldset>
                    </c:if>
                    
                    <%-- <div id="painel-comentarios-${atividade.id}">
                        <fan:comments tipo="<%=br.com.fanaticosporviagens.model.entity.Comentario.TipoComentario.ITEM_DIARIO.name()%>" 
                                      id="comentario-${atividade.id}" idAlvo="${atividade.relato.id}" inputClass="span8"
                                      imgSize="mini-avatar" inputType="text" buttonOnSameLine="true" />
                    </div> --%>
                    
                </fieldset>
                
              </section>
          
            </c:if>
            
          </c:forEach>
          
        </c:if>
        
      </div>
      
      <div id="fb-root"></div>
  
    </div>
    
    <div class="span4">
        
    </div>
    
  </fieldset>
  
</div>

<script>

    jQuery(function() {
    	
        $('body').scrollspy({
        	offset : -400
        });
        
        $('.bs-docs-sidenav').affix({
          offset: {
            top: 460,
            bottom: 570
          }
        });
        
        $('.btn-exibir-painel').on('click', function(e) {
            e.preventDefault();
            
            var painelId = $(this).attr('data-painel-id');
            
            if ($(this).attr('class').indexOf('active') === -1) {
                $('#' + painelId).css('display', '');
            } else {
                $('#' + painelId).css('display', 'none');
            }
        });
        
        $('.bs-docs-sidenav i.mudar-dia').on('click', function(e) {
        	var dia = $(this).data('proximo-dia');
        	$('.jcarousel-skin-tango a[data-dia=' + dia + ']').click();
        })

        $('a[rel="slideShow"]').fancybox({
            transitionIn      : 'elastic',
            transitionOut     : 'elastic',
            type              : 'image',
            autoScale : false,
            autoDimensions : false,
            width : 560,
            height : 340,
            speedIn: 400, 
            speedOut: 200, 
            overlayShow: true,
            overlayOpacity: 0.1,
            hideOnContentClick: true,
            'titleFormat' : function(title, currentArray, currentIndex, currentOpts) {
                return '<span>Foto ' + (currentIndex + 1) + ' / ' + currentArray.length + ' ' + title + '</span>';
            },
            titlePosition: 'inside'
        });        
    });
    
</script>

src/main/webapp/WEB-INF/views/planoViagem/diario/informacaoAtividade.jsp
<%@page import="br.com.fanaticosporviagens.model.entity.Avaliacao"%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib prefix="joda" uri="http://www.joda.org/joda/time/tags" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="fan" %>

<c:choose>
  
  <c:when test="${empty atividade}">
  
    <h3>
        <b class="green">
            ${diario.viagem.nome} 
        </b> 
    </h3>
    <br/>
    
    <div>
        <div>
          <h2>
            <c:forEach items="${diario.viagem.cidades}" var="cidade" varStatus="status">
                <a href="#">${cidade.nomeComSiglaEstado}</a>
                ${not status.last ? ' - ' : ''}
            </c:forEach>
            <p>
            <small>${diario.viagem.periodoFormatado}</small>
            </p>
          </h2>
        </div>
    </div>

    <div>
      <p class="texto-blog">
        ${diario.viagem.descricao}
      </p>
    </div>                    
      
  </c:when>
  <c:otherwise>
  
    <h3>
        <b class="green">
            ${diaViagem.numero}º dia - 
        </b> 
        ${diaViagem.diaSemanaLongoDiaMesComMesLongo}
    </h3>
    <br/>
        
    <h4 class="green">
        <c:choose>
          <c:when test="${not empty atividade.titulo}">
            ${atividade.titulo}
          </c:when>
          <c:otherwise>
            <c:choose>
              <c:when test="${atividade.hospedagem}">Hospedagem em</c:when>
              <c:otherwise>Visitando</c:otherwise>
            </c:choose>
            <a href="#" target="_blank">${atividade.local.nome}</a>
          </c:otherwise>
        </c:choose>
    </h4>
      
    <c:if test="${atividade.possuiRelato}">
        <span class="texto-blog">
            ${atividade.relato.texto}
        </span>
    </c:if>

  </c:otherwise>

</c:choose>

src/main/webapp/WEB-INF/views/planoViagem/diario/slideShow.jsp
<%@page import="br.com.fanaticosporviagens.model.entity.Avaliacao"%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib prefix="joda" uri="http://www.joda.org/joda/time/tags" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="fan" %>
