src/main/java/br/com/fanaticosporviagens/model/entity/Atividade.java
package br.com.fanaticosporviagens.model.entity;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;

import br.com.fanaticosporviagens.infra.model.entity.GenericEnumUserType;

/**
 * Campos futuros na atividade
 * 1. Fotos
 *
 * @author gustavo
 * @author Carlos
 *
 */
@Entity
@Table(name = "viagem_atividade")
@TypeDefs(value = {
        @TypeDef(name = "TipoTransporte", typeClass = GenericEnumUserType.class, parameters = { @Parameter(name = "enumClass", value = "br.com.fanaticosporviagens.model.entity.TipoTransporte") }),
        @TypeDef(name = "TipoAtividade", typeClass = GenericEnumUserType.class, parameters = { @Parameter(name = "enumClass", value = "br.com.fanaticosporviagens.model.entity.TipoAtividade") }) })
public class Atividade {

    @Column(name = "anotacoes", nullable = true)
    private String anotacoes;

    @Column(name = "data_hora_fim", nullable = true)
    private Date dataHoraFim;

    @Column(name = "data_hora_inicio", nullable = true)
    private Date dataHoraInicio;

    @Column(name = "descricao_atividade", nullable = true)
    private String descricao;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_viagem_dia", nullable = true)
    private DiaViagem dia;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_viagem_dia_fim", nullable = true)
    private DiaViagem diaFim;

    @Id
    @Column(name = "id_viagem_atividade")
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_viagem_atividade_anterior", nullable = true, insertable = false)
    private Atividade itemAnterior;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_viagem_atividade_proximo", nullable = true, insertable = false)
    private Atividade itemProximo;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_local", nullable = true)
    private Local local;

    @Embedded
    @AttributeOverrides({ @AttributeOverride(name = "nome", column = @Column(name = "destino_nome_local")),
        @AttributeOverride(name = "descricao", column = @Column(name = "destino_descricao_local")),
        @AttributeOverride(name = "endereco.descricao", column = @Column(name = "destino_endereco_local")),
        @AttributeOverride(name = "endereco.bairro", column = @Column(name = "destino_bairro_local")),
        @AttributeOverride(name = "endereco.cep", column = @Column(name = "destino_cep_local")) })
    private LocalEnderecavelNaoCadastradoAtividade localDestinoNaoCadastrado = new LocalEnderecavelNaoCadastradoAtividade();

    @Embedded
    @AttributeOverrides({ @AttributeOverride(name = "nome", column = @Column(name = "local_nome")),
        @AttributeOverride(name = "descricao", column = @Column(name = "local_descricao")),
        @AttributeOverride(name = "endereco.descricao", column = @Column(name = "local_endereco")),
        @AttributeOverride(name = "endereco.bairro", column = @Column(name = "local_bairro")),
        @AttributeOverride(name = "endereco.cep", column = @Column(name = "local_cep")) })
    private LocalEnderecavelNaoCadastradoAtividade localNaoCadastrado = new LocalEnderecavelNaoCadastradoAtividade();

    @Embedded
    @AttributeOverrides({ @AttributeOverride(name = "nome", column = @Column(name = "origem_nome_local")),
        @AttributeOverride(name = "descricao", column = @Column(name = "origem_descricao_local")),
        @AttributeOverride(name = "endereco.descricao", column = @Column(name = "origem_endereco_local")),
        @AttributeOverride(name = "endereco.bairro", column = @Column(name = "origem_bairro_local")),
        @AttributeOverride(name = "endereco.cep", column = @Column(name = "origem_cep_local")) })
    private LocalEnderecavelNaoCadastradoAtividade localOrigemNaoCadastrado = new LocalEnderecavelNaoCadastradoAtividade();

    @Column
    private Integer ordem;

    @Column
    private boolean paga;

    @Column
    private boolean reservada;

    @Type(type = "TipoAtividade")
    @Column(name = "tipo_atividade", nullable = true)
    private TipoAtividade tipo;

    @Column(name = "titulo_atividade", nullable = true)
    private String titulo;

    @Type(type = "TipoTransporte")
    @Column(name = "transporte_codigo", nullable = true)
    private TipoTransporte transporte;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "transporte_destino_id_local", nullable = true)
    private Local transporteLocalDestino;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "transporte_origem_id_local", nullable = true)
    private Local transporteLocalOrigem;

    @Column(name = "valor_atividade", nullable = true)
    private BigDecimal valor;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_viagem", nullable = true)
    private Viagem viagem;

    private void definirTipoPeloLocal() {
        if (this.tipo == null && this.local != null) {
            if (this.local instanceof Atracao || this.local instanceof LocalInteresseTuristico) {
                this.tipo = TipoAtividade.VISITA_ATRACAO;
            } else if (this.local instanceof Restaurante) {
                this.tipo = TipoAtividade.ALIMENTACAO;
            } else if (this.local instanceof Hotel) {
                this.tipo = TipoAtividade.HOSPEDAGEM;
            }
        }
    }

    @SuppressWarnings("rawtypes")
    @Override
    public boolean equals(final Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Atividade other = (Atividade) obj;
        if (this.id == null) {
            if (other.getId() != null)
                return false;
        } else if (!this.id.equals(other.getId()))
            return false;
        return true;
    }

    public String getAnotacoes() {
        return this.anotacoes;
    }

    public LocalGeografico getCidadeDestinoTransporte() {
        if (this.transporteLocalDestino != null) {
            if (this.transporteLocalDestino instanceof Cidade || this.transporteLocalDestino instanceof LocalInteresseTuristico) {
                return (LocalGeografico) this.transporteLocalDestino;
            } else if (this.transporteLocalDestino instanceof LocalEnderecavel) {
                return this.transporteLocalDestino.getLocalizacao().getCidade().getLocal();
            }
        }
        return null;
    }

    public LocalGeografico getCidadeOrigemTransporte() {
        if (this.transporteLocalOrigem != null) {
            if (this.transporteLocalOrigem instanceof Cidade || this.transporteLocalOrigem instanceof LocalInteresseTuristico) {
                return (LocalGeografico) this.transporteLocalOrigem;
            } else if (this.transporteLocalOrigem instanceof LocalEnderecavel) {
                return this.transporteLocalOrigem.getLocalizacao().getCidade().getLocal();
            }
        }
        return null;
    }

    public Atividade getCopia(final DiaViagem diaCopia) {
        return getCopia(null, diaCopia);
    }

    public Atividade getCopia(final Viagem viagemCopia) {
        return getCopia(viagemCopia, null);
    }

    private Atividade getCopia(final Viagem viagemCopia, final DiaViagem diaCopia) {
        final Atividade copia = new Atividade();

        copia.setViagem(viagemCopia);
        copia.setDia(diaCopia);

        copia.setTipo(getTipo());
        copia.setLocal(getLocal());
        copia.setTitulo(getTitulo());
        copia.setAnotacoes(getAnotacoes());
        copia.setPaga(isPaga());
        copia.setReservada(isReservada());
        copia.setLocalNaoCadastrado(getLocalNaoCadastrado());
        copia.setLocalOrigemNaoCadastrado(getLocalOrigemNaoCadastrado());
        copia.setLocalDestinoNaoCadastrado(getLocalDestinoNaoCadastrado());

        copia.setTransporte(getTransporte());
        copia.setTransporteLocalOrigem(getTransporteLocalOrigem());
        copia.setTransporteLocalDestino(getTransporteLocalDestino());

        copia.setDataHoraFim(getDataHoraFim());
        copia.setDataHoraInicio(getDataHoraInicio());
        copia.setDescricao(getDescricao());
        copia.setValor(getValor());

        return copia;
    }

    public Date getDataHoraFim() {
        return this.dataHoraFim;
    }

    public Date getDataHoraInicio() {
        return this.dataHoraInicio;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public String getDescricaoDono() {
        if (this.viagem != null) {
            return "Item da viagem";
        }
        return "Item do " + this.dia.getDescricao();
    }

    public DiaViagem getDia() {
        return this.dia;
    }

    public DiaViagem getDiaFim() {
        return this.diaFim;
    }

    public String getEmail() {
        if (this.local == null) {
            return null;
        }
        return this.local.getEmail();
    }

    public String getEndereco() {
        if (this.local != null) {
            final Endereco endereco = this.local.getEndereco();

            if (endereco != null) {
                final StringBuilder enderecoFormatado = new StringBuilder();

                if (endereco.getDescricao() != null && !endereco.getDescricao().trim().isEmpty()) {
                    enderecoFormatado.append(endereco.getDescricao());
                    if (endereco.getBairro() != null && !endereco.getBairro().trim().isEmpty()) {

src/main/java/br/com/fanaticosporviagens/model/entity/Endereco.java
package br.com.fanaticosporviagens.model.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * @author André Thiago
 * 
 */
@Embeddable
public class Endereco {

    @Column(name = "bairro")
    private String bairro;

    @Column(name = "cep")
    private String cep;

    @Column(name = "endereco")
    private String descricao;

    public Endereco() {
    }

    public Endereco(final String descricao) {
        this.descricao = descricao;
    }

    @Override
    public boolean equals(final Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Endereco other = (Endereco) obj;
        if (this.cep == null) {
            if (other.cep != null)
                return false;
        } else if (!this.cep.equals(other.cep))
            return false;
        if (this.descricao == null) {
            if (other.descricao != null)
                return false;
        } else if (!this.descricao.equals(other.descricao))
            return false;
        return true;
    }

    public String getBairro() {
        return this.bairro;
    }

    public String getCep() {
        return this.cep;
    }

    public String getDescricao() {
        return this.descricao;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.cep == null) ? 0 : this.cep.hashCode());
        result = prime * result + ((this.descricao == null) ? 0 : this.descricao.hashCode());
        return result;
    }

    public void setBairro(final String bairro) {
        this.bairro = bairro;
    }

    public void setCep(final String cep) {
        this.cep = cep;
    }

    public void setDescricao(final String descricao) {
        this.descricao = descricao;
    }

}

src/main/java/br/com/fanaticosporviagens/viagem/model/repository/AtividadePlanoRepository.java
package br.com.fanaticosporviagens.viagem.model.repository;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import br.com.fanaticosporviagens.infra.model.repository.GenericCRUDRepository;
import br.com.fanaticosporviagens.model.entity.AtividadePlano;

/**
 * @author Pedro Sebba (sebbaweb@gmail.com)
 * 
 */
@Repository
public class AtividadePlanoRepository extends GenericCRUDRepository<AtividadePlano, Long> {

    public List<AtividadePlano> consultarAtividadesViagem(final Long idViagem) {

        final StringBuilder select = new StringBuilder();

        select.append("SELECT a ");

        select.append("  FROM AtividadePlano a ");
        select.append(" WHERE a.viagem.id = :idViagem ");
        select.append(" ORDER BY a.dataInicio, a.ordem, a.dia ");

        final Map<String, Object> parametros = new HashMap<String, Object>();
        parametros.put("idViagem", idViagem);

        return this.searchRepository.consultaHQL(select.toString(), parametros);

    }
}

src/main/java/br/com/fanaticosporviagens/viagem/model/repository/PlanoViagemRepository.java
package br.com.fanaticosporviagens.viagem.model.repository;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import br.com.fanaticosporviagens.infra.model.repository.GenericCRUDRepository;
import br.com.fanaticosporviagens.infra.model.repository.GenericSearchRepository;
import br.com.fanaticosporviagens.model.entity.PlanoViagem;

/**
 * @author Pedro Sebba (sebbaweb@gmail.com)
 * 
 */
@Repository
public class PlanoViagemRepository extends GenericCRUDRepository<PlanoViagem, Long> {

    @Autowired
    private GenericSearchRepository searchRepository;

    public List<PlanoViagem> consultarViagensUsuario(final Long idUsuario) {
        final StringBuilder select = new StringBuilder();

        select.append("SELECT v.id, ");
        select.append("       v.nome, ");
        select.append("       v.\"dataInicio\", ");
        select.append("       v.\"dataFim\" ");

        select.append("  FROM viagem v ");
        select.append(" WHERE v.criador = :idUsuario");
        final Map<String, Object> parametros = new HashMap<String, Object>();

        parametros.put("idUsuario", idUsuario);

        return this.searchRepository.consultaSQL(select.toString(), parametros, PlanoViagem.class);

    }
}

src/main/webapp/WEB-INF/views/viagem/planejamento/iframe.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" session="true" trimDirectiveWhitespaces="true" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%>
<%@ taglib uri="http://htmlcompressor.googlecode.com/taglib/compressor" prefix="compress" %>

<!DOCTYPE html>
<html>
<c:choose>
    <c:when test="${fn:toLowerCase(pageContext.request.scheme) == 'https'}">
        <c:set var="reqScheme" value="https" />
    </c:when>
    <c:otherwise>
        <c:set var="reqScheme" value="http" />
    </c:otherwise>
</c:choose>

<compress:html enabled="true" compressJavaScript="true" jsCompressor="closure" compressCss="true">

<link rel="stylesheet" href="<c:url value="/wro/mainResponsive.css" />" type="text/css" />

<link href='${reqScheme}://fonts.googleapis.com/css?family=Open+Sans+Condensed:light&v1' rel='stylesheet' type='text/css'>
<link href='${reqScheme}://fonts.googleapis.com/css?family=PT+Sans+Narrow' rel='stylesheet' type='text/css'>

<c:choose>
  <c:when test="${isMobile}">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/resources/styles/baseResponsiveMobile.css" type="text/css" media="screen, projection"/>
  </c:when>
  <c:otherwise>
    <link rel="stylesheet" href="${pageContext.request.contextPath}/resources/styles/baseResponsiveDesktop.css" type="text/css" media="screen, projection"/>
  </c:otherwise>
</c:choose>

<script type="text/javascript" src="<c:url value="/wro/mainResponsive.js"/>" ></script>

<c:if test="${not unsuportedIEVersion}">
  <script type="text/javascript" src="${reqScheme}://www.panoramio.com/wapi/wapi.js?v=1&hl=pt_BR"></script>
</c:if>


<style>
label {
    font-weight: normal;
}
</style>

<body>

    <div>

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li><a id="btn-tab-adicionar-atividade" href="#tab-adicionar-atividade" role="tab" data-toggle="tab" style="font-size: 15px;">Já sei onde quero ir</a></li>
            <li><a id="btn-tab-selecionar-atividades" href="#tab-selecionar-atividades" role="tab" data-toggle="tab" style="font-size: 15px;">Quero sugestões</a></li>
        </ul>

        <div id="iframe-body">
            <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane" id="tab-adicionar-atividade">
                  <div id="tab-adicionar-atividade-body">
                  </div>
                  
                  <div id="editar-atividade-modal-footer-incluir" class="modal-footer">
                    <button id="btnCancelarAtividade" class="btn btn-default" data-dismiss="modal" aria-hidden="true">
                        <span class="glyphicon glyphicon-remove"></span>
                        Cancelar
                    </button>
                    <button id="btnIncluirAtividade" class="btn btn-primary" data-loading-text="Salvando...">
                        <span class="glyphicon glyphicon-floppy-saved"></span>
                        Salvar
                    </button>
					<button id="btnIncluirVariasAtividades" class="btn btn-info" data-loading-text="Salvando...">
                    	<span class="glyphicon glyphicon-floppy-open"></span>
                    	Salvar e adicionar +
                	</button>                  
                  </div>
                </div>
                <div class="tab-pane" id="tab-selecionar-atividades"></div>
            </div>        
        </div>

    </div>
</body>

<script>
$(document).ready(function () {

    $('#btn-tab-adicionar-atividade').click(function (e) {
        
        var tipoAtividade = '${tipoAtividade}';
    
        $('#tab-adicionar-atividade-body').load('<c:url value="/viagem/${viagem.id}/criarAtividade/"/>' + tipoAtividade + '?diaInicio=${diaInicio}&diaFim=${diaFim}', function() {
        
            /*$('#editar-atividade-modal-footer-incluir').show();
            $('#inputDia option[value="' + dia + '"]').attr('selected', 'selected');
            $('#inputDia').trigger('change');
            
            if (tipo) {
                $('#selectTipoAtividade').find('ul.dd-options li').each(function(index) {
                    if ($(this).find('input.dd-option-value').val() == tipo) {
                        $('#selectTipoAtividade').ddslick('select', { index: index });
                    }
                    $('input[name="nomeLocal"]').focus();
                })
            } else {
                $('#selectTipoAtividade').focus();
            }*/

            var height = $('#iframe-body').css('height');
            
            height = height.substring(0, height.indexOf('px')); 
            height = parseInt(height) + 150;
            
            parent.$('#sugestoes-modal').css('overflow-y', 'auto');
            parent.$('#sugestoes-modal').find('div.modal-dialog').css('height', height + 'px');
        })
    });

    $('#btn-tab-selecionar-atividades').click(function (e) {
        $('#tab-selecionar-atividades').load('<c:url value="/viagem/${viagem.id}/${urlPathCidadeSelecionada}/sugestoesLugares?tipoLocal=${tipoLocal}&diaInicio=${diaInicio} "/>', function(response) {
            
            var height = $('#iframe-body').css('height');
            
            height = height.substring(0, height.indexOf('px')); 
            height = parseInt(height) + 150;
            
            //parent.$('#sugestoes-modal').find('div.modal-dialog').css('height', '100%');
            
            $('#tab-selecionar-atividades').html(response)
            parent.$('#sugestoes-modal').css('overflow-y', 'hidden');
            parent.$('#sugestoes-modal').find('#scroll-div').css('height', $(window).height());
            $('#scroll-div').css('height', $(window).height() - 100);
            $('#scroll-div').find('div.lista-locais').css('min-height', $(window).height() + 100);

            if ($.browser.chrome) {
            } else if ($.browser.mozilla) {
                $('#suggestions-div').css('min-height', '');
                $('#suggestions-div').css('height', '800px');
            } else if ($.browser.msie) {
            }
            
        });
    });
    
    $(document).on('click', '#btnCancelarAtividade', function (e) {
        /*if($('#inputAtualizarQuandoFechar').val() == 'sim') {
            $('#inputAtualizarQuandoFechar').val('nao');
            parent.recarregarPagina();
        }*/
        parent.$('#sugestoes-modal').modal('hide');
    });
    
    $(document).on('click', '#btnIncluirAtividade', function (e) {
        e.preventDefault();
        $(this).button('loading');
        parent.salvarAtividade($('#formIncluirAtividade'), $(this), true);
        parent.$('#sugestoes-modal').modal('hide');
    });
    
    $(document).on('click', '#btnIncluirVariasAtividades', function (e) {
        e.preventDefault();
        $(this).button('loading');
        parent.salvarAtividade($('#formIncluirAtividade'), $(this), false);
        $('#inputAtualizarQuandoFechar').val('sim');
        $('input[name="nomeLocal"]').focus();
    });
    
    $(document).on('click', '#btn-salvar-atividade', function (e) {
        e.preventDefault();
        $(this).button('loading');
        parent.salvarAtividade($('#formAlterarAtividade'), $(this), true);
        parent.$('#sugestoes-modal').modal('hide');
    });
    
    $(document).on('change', 'select[name="diaInicio"][rel="HOSPEDAGEM"]', function (e) {
        var dia = $(this).val();
        $('select[name="itemDono"]').find('option[value="' + dia + '"]').attr('selected', 'selected');
        atualizarOpcoesDataFimAtividade('HOSPEDAGEM');
    });
    
    var acao = '${acao}';
    if (acao !== '') {
        var $tabAtual = $('#btn-tab-' + acao);
        if ($tabAtual.attr('id') != null) {
            $tabAtual.click();
        } else {
            $('#btn-tab-adicionar-atividade').click();
        }
        
    } else {
        $('#btn-tab-adicionar-atividade').click();
    }
    
});
</script>
</compress:html>
</html>

src/main/webapp/WEB-INF/views/viagem/planejamento/listaParticipantes.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" trimDirectiveWhitespaces="true" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="fan" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<ul class="list-group">

  <c:forEach var="participante" items="${participantes}">
    <li id="li-participante-${participante.id}" class="list-group-item" style="padding-top: 5px; padding-bottom: 0px">
      <c:if test="${not empty participante.usuario.id}">
        <c:set var="nome" value="${participante.usuario.nome}"/>
        <fan:userAvatar user="${participante.usuario}" enableLink="false" showImgAsCircle="true" showFacebookMark="false"
                  		marginLeft="0" displayName="false" displayNameTooltip="false" width="30" height="30" 
                  		showFrame="false" showShadow="false" />
      </c:if>
      <c:if test="${empty participante.usuario.id}">
        <div style="float: left; margin-left:0px; margin-right: 5px;"> 
          <div style="margin-bottom: 5px; position: relative;"> 
		    <img class="img-circle" src="<c:url value="/resources/images/anonymous.png"/>" style="background-color: #FEFEFE; " width="30" height="30">      
          </div> 
        </div>
        <c:set var="nome" value="${participante.email}"/>
      </c:if>
        <div class="row" style="padding-top: 5px;">
         	<div class="col-xs-5" style="padding-left: 1px;">${nome}</div>
         	<div class="col-xs-1">
         	  <c:if test="${participante.viaja and participante.faixaEtaria < 2}">
	         	  <c:choose>
	         	    <c:when test="${participante.podeEditarViagem}">
	         		  <span class="glyphicon glyphicon-star btn-xs" title="Pode alterar todo o roteiro"></span>
	                </c:when>
	         	    <c:when test="${participante.podeAdicionarAtividade}">
	         		  <span class="glyphicon glyphicon-star-empty btn-xs" title="Pode incluir atividades"></span>
	                </c:when>
	         	    <c:otherwise>
	         		  <span class="glyphicon glyphicon-eye-open btn-xs" title="Pode ver o roteiro"></span>
	                </c:otherwise>
	              </c:choose>
              </c:if>
         	</div>
         	<div class="col-xs-3">
         	  <c:if test="${participante.viaja and participante.faixaEtaria < 2 }">
         		<c:choose>
         		  <c:when test="${participante.confirmado}">
         		    Confirmado
         		  </c:when>
         		  <c:when test="${participante.confirmado == false}">
         		  	Não confirmou
         		  </c:when>
         		  <c:otherwise>
         		    A confirmar
         		  </c:otherwise>
         		</c:choose>
         	  </c:if>
         	</div>
         	<div class="col-xs-1 btn-xs pull-right" style="margin: 0; padding: 0;">
         	  <c:if test="${participante.viaja}">
         	    <a href="#" class="btn-editar-viajante" title="Editar" style="color: #999" data-id-participante="${participante.id}" data-nome-participante="${participante.nome}">
         		  <span class="glyphicon glyphicon-edit"></span>
         	    </a>
         	  </c:if>
         	  <a href="#" class="btn-remover-viajante" data-id-participante="${participante.id}" title="Remover" style="color: #999">
         		<span class="glyphicon glyphicon-remove"></span>
         	  </a>
         	</div>
        </div>
    </li>
  </c:forEach>

src/main/webapp/WEB-INF/views/viagem/planejamento/listaSugestoesLugares.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" trimDirectiveWhitespaces="true" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="fan" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

	<c:set var="idsLocaisSelecionados" value=""/>
	<c:forEach var="idLocal" items="${locaisJaSelecionados}"><c:set var="idsLocaisSelecionados" value="${idsLocaisSelecionados},${idLocal}"/></c:forEach>
	<c:forEach var="idLocal" items="${locaisJaSelecionadosImperdiveis}"><c:set var="idsLocaisSelecionadosImperdiveis" value="${idsLocaisSelecionadosImperdiveis},${idLocal}"/></c:forEach>
    
    <fan:listaLocais locaisEmDestaque="${sugestoesLocais}" urlProximos="/viagem/${viagem.id}/${destino.urlPath}/sugestoesLugares?filtro=${filtro}&tipoLocal=${tipoLocal}&start=${proximasSugestoes}&tags=${tags}&estrelas=${estrelas}&bairros=${bairros}&locaisJaSelecionados=${idsLocaisSelecionados}&locaisJaSelecionadosImperdiveis=${idsLocaisSelecionadosImperdiveis}&recomendacao=${recomendacao}&columns=${columns}&columnSize=${columnSize}" 
                     photoHeight="120" photoSize="small" cardOrientation="horizontal" columns="${not empty columns ? columns : 1}" columnSize="${not empty columnSize ? columnSize : 12}" showActions="false" showAdditionalInfo="false"
                     showAddToPlanButton="false" showNotaGeral="false" showViajantesJaForam="false" showAmigosJaForam="false" showReservarBooking="false" showBotaoAdicionar="false"
                     useButtonsRecomendacao="${recomendacao}"
                     style="${not isMobile ? 'padding-top: 0px;' : ''}" 
                     cardStyle="${isMobile ? 'padding-right: 0px; padding-left: 0px;' : 'min-height: 120px;'};"
                     titleStyle="font-size: .8em;" />
